version: "3.9"
name: ani-gamer-plus

services:
  ani-gamer-plus:
    build:
      context: .
    image: anigamerplus
    container_name: "ani-gamer-plus"
    volumes:
      - "./downloads:/app/bangumi"
      - "./cookie.txt:/app/cookie.txt"
      - "./config.json:/app/config.json"
    ports:
      - "8001:5000"
    restart: unless-stopped
